CREATE TABLE IF NOT EXISTS accounts (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `category` VARCHAR(32) NOT NULL,
    `identification` VARCHAR(256) NOT NULL,
    `password` VARCHAR(256) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE `users` DROP COLUMN `password`;
ALTER TABLE `users` DROP COLUMN `email`;