// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/country": {
            "get": {
                "description": "get a list of all available countires",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "Get all country",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CountryResponseDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/trip": {
            "get": {
                "description": "get trip",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trip"
                ],
                "summary": "Get all trip",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Trip"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "User registration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "User login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CountryResponseDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "CA"
                },
                "currency": {
                    "type": "string",
                    "example": "$"
                },
                "name": {
                    "type": "string",
                    "example": "Canada"
                }
            }
        },
        "dto.UserRequestDTO": {
            "type": "object",
            "required": [
                "Email",
                "Password"
            ],
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "test@email.com"
                },
                "Password": {
                    "type": "string",
                    "example": "test-password"
                }
            }
        },
        "entities.Trip": {
            "type": "object",
            "properties": {
                "Budget": {
                    "type": "number",
                    "example": 2000.12
                },
                "CountryId": {
                    "type": "integer",
                    "example": 1
                },
                "CreatedAt": {
                    "type": "string",
                    "example": "2023-05-29"
                },
                "DeletedAt": {
                    "type": "string",
                    "example": "2023-05-29"
                },
                "Description": {
                    "type": "string",
                    "example": "sample-description"
                },
                "EndDateTime": {
                    "type": "string",
                    "example": "2023-08-29"
                },
                "ID": {
                    "type": "integer",
                    "example": 1
                },
                "Name": {
                    "type": "string",
                    "example": "sample-name"
                },
                "StartDateTime": {
                    "type": "string",
                    "example": "2023-05-29"
                },
                "UpdatedAt": {
                    "type": "string",
                    "example": "2023-05-29"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Pocket Mate API",
	Description:      "This is a pocket-mate server api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
