FROM golang:alpine AS builder

WORKDIR /src/app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o ./run .


FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /src/app/run .

EXPOSE 8080

CMD ["./run"]

