FROM golang:1.18-alpine

ARG APP_URL \
    PORT \
    ACCESS_TOKEN_SECRET \
    ACCESS_TOKEN_EXPIRED_AT \
    DB_HOST \
    DB_NAME \
    DB_USER \
    DB_PASSWORD \
    DB_PORT

ENV APP_URL=${APP_URL} \
    PORT=${PORT} \
    ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET} \
    ACCESS_TOKEN_EXPIRED_AT=${ACCESS_TOKEN_EXPIRED_AT} \
    DB_HOST=${DB_HOST} \
    DB_NAME=${DB_NAME} \
    DB_USER=${DB_USER} \
    DB_PASSWORD=${DB_PASSWORD} \
    DB_PORT=${DB_PORT}

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go mod download
RUN go build -o dist/cmd ./cmd

EXPOSE 8080

CMD ["./dist/cmd"]
